// Reference phrases transcribed from the user-provided category workbook.
// Nine source categories are intentionally mapped to six application categories.
export const referenceGroups = [
  {
    "sourceCategory": "1. Control digital",
    "category": "control",
    "phrases": [
      "Mándame tu ubicación en tiempo real.",
      "Activa la ubicación, quiero saber dónde estás.",
      "Si no tienes nada que ocultar, dame tu clave.",
      "Déjame revisar tu celular.",
      "Enséñame con quién hablas.",
      "Pásame captura de tus chats.",
      "¿Por qué estabas en línea y no me respondiste?",
      "Vi que le diste like a esa persona.",
      "¿Quién es ese que te reaccionó la historia?",
      "Mándame foto de dónde estás.",
      "Haz videollamada para comprobar que estás en tu casa.",
      "Quiero revisar tus seguidores.",
      "Borra a esa persona de Instagram.",
      "No me gusta que sigas a tu ex.",
      "Dame tu contraseña de Instagram.",
      "Quiero tener tu WhatsApp abierto en mi computadora.",
      "Mándame captura de tu galería.",
      "¿Por qué borraste mensajes?",
      "No pongas historias si vas a salir así.",
      "Quiero ver tus conversaciones archivadas.",
      "Tienes que contestarme apenas veas mis mensajes.",
      "No me dejes en visto.",
      "¿Por qué quitaste la última conexión?",
      "Activa el visto, no me gusta que lo ocultes.",
      "Si estamos juntos, no deberías tener privacidad conmigo.",
      "Tu celular también es mío.",
      "No quiero que tengas clave en el celular.",
      "Mándame una foto ahora para saber con quién estás.",
      "¿Por qué no subiste una foto conmigo?",
      "Voy a revisar tus redes porque tú no me cuentas todo."
    ]
  },
  {
    "sourceCategory": "2. Celos coercitivos",
    "category": "control",
    "phrases": [
      "Seguro estás hablando con alguien más.",
      "Si me amaras, no hablarías con esa persona.",
      "Me das motivos para desconfiar.",
      "Tú provocas mis celos.",
      "No me gusta cómo te mira esa persona.",
      "Bloquéalo o terminamos.",
      "No quiero que salgas con tus amigas.",
      "Te vistes así para llamar la atención.",
      "¿Para quién te arreglaste tanto?",
      "Desde que conociste a esa gente cambiaste.",
      "No me gusta que tengas amigos hombres.",
      "No me gusta que tengas amigas tan intensas.",
      "Esa persona quiere algo contigo, no te hagas.",
      "Me estás faltando el respeto por hablarle.",
      "Si sales sin mí, no cuentes conmigo.",
      "No me gusta que bailes con nadie.",
      "¿Por qué te ríes tanto con esa persona?",
      "A mí no me engañas, yo sé cómo eres.",
      "Me haces quedar como tonto.",
      "Si me quieres, demuéstramelo alejándote de esa persona.",
      "No soporto verte conectada y que no sea conmigo.",
      "Me enferma imaginarte con alguien más.",
      "Tú sabes que soy celoso, no me provoques.",
      "Tus amistades son una amenaza para la relación.",
      "No necesito pruebas, lo siento.",
      "Si no estás haciendo nada malo, no te debería molestar que pregunte.",
      "Me ocultas cosas porque sabes que estás mal.",
      "Yo solo te celo porque me importas.",
      "Mis celos son culpa tuya.",
      "Prefiero que no salgas para evitar problemas."
    ]
  },
  {
    "sourceCategory": "3. Amenazas",
    "category": "threat",
    "phrases": [
      "Te vas a arrepentir.",
      "Si me dejas, vas a ver.",
      "No sabes de lo que soy capaz.",
      "Voy a publicar tus fotos.",
      "Le voy a contar todo a tu familia.",
      "Voy a hacer que todos sepan quién eres.",
      "Nadie te va a creer.",
      "Te voy a destruir la reputación.",
      "Puedo hacerte quedar mal.",
      "Si hablas, te va peor.",
      "No me provoques.",
      "Tengo capturas, acuérdate.",
      "Si no vuelves conmigo, subo todo.",
      "Te voy a buscar donde estés.",
      "Sé dónde vives.",
      "Sé dónde trabajas.",
      "No me obligues a hacer algo.",
      "Tú sabes que puedo hacerte daño.",
      "Voy a contar cosas tuyas.",
      "Voy a mandarle todo a tus amistades.",
      "Te voy a denunciar aunque sea mentira.",
      "Voy a decir que tú fuiste la mala.",
      "Vas a perder todo por mi culpa.",
      "No vas a poder estar tranquila.",
      "Si no eres mía, no eres de nadie.",
      "Te voy a arruinar la vida.",
      "No juegues conmigo.",
      "Voy a hacer que te boten del trabajo.",
      "Tengo cosas tuyas guardadas.",
      "Si me bloqueas, voy a aparecer igual."
    ]
  },
  {
    "sourceCategory": "4. Violencia psicológica por abandono, humillación o castigo emocional",
    "category": "manipulation",
    "phrases": [
      "Te voy a ignorar para que aprendas.",
      "No mereces que te responda.",
      "Ya no me importas.",
      "Haz lo que quieras, me da igual.",
      "Eres demasiado intensa.",
      "Nadie te va a aguantar.",
      "Siempre arruinas todo.",
      "Me das vergüenza.",
      "Por eso nadie se queda contigo.",
      "Eres un problema.",
      "No sirves para una relación.",
      "Estoy cansado de tus dramas.",
      "Te desapareces de mi vida cuando me molestas.",
      "No te voy a hablar hasta que entiendas.",
      "Si lloras, es tu problema.",
      "Qué ridícula eres.",
      "Mejor cállate.",
      "Contigo no se puede hablar.",
      "Me aburres.",
      "No eres tan especial como crees.",
      "Deberías agradecer que estoy contigo.",
      "Cualquiera sería mejor que tú.",
      "Siempre tengo que soportarte.",
      "Me desaparecí porque necesitabas aprender.",
      "No te respondí porque no valía la pena.",
      "Cuando dejes de exagerar, hablamos.",
      "No mereces explicaciones.",
      "No eres prioridad.",
      "Te castigo con silencio porque no entiendes de otra forma.",
      "Vuelvo cuando me dé la gana."
    ]
  },
  {
    "sourceCategory": "5. Gaslighting",
    "category": "manipulation",
    "phrases": [
      "Eso nunca pasó.",
      "Yo nunca dije eso.",
      "Estás inventando.",
      "Estás loca.",
      "Todo te lo imaginas.",
      "Eres demasiado sensible.",
      "Siempre exageras.",
      "Estás malinterpretando todo.",
      "Eso solo está en tu cabeza.",
      "Tú tienes problemas.",
      "Necesitas ayuda.",
      "Yo solo estaba bromeando.",
      "No fue para tanto.",
      "Te encanta hacer drama.",
      "Nadie más lo vería así.",
      "Tú eres la tóxica.",
      "Me estás acusando sin razón.",
      "Ya no sé cómo hablarte porque todo te ofende.",
      "Te acuerdas mal.",
      "Estás confundiendo las cosas.",
      "Yo no hice nada, tú lo provocaste.",
      "Siempre cambias la historia.",
      "Te haces la víctima.",
      "Tú misma te lastimas pensando así.",
      "No sé de dónde sacas esas ideas.",
      "Eso no fue violencia, fue una discusión normal.",
      "Si te dolió, es porque eres débil.",
      "Nadie te va a tomar en serio.",
      "Otra vez con tus traumas.",
      "Yo soy el único que te dice la verdad."
    ]
  },
  {
    "sourceCategory": "6. Outing",
    "category": "sexual",
    "phrases": [
      "Le voy a contar a tu familia que eres bisexual.",
      "Nadie sabe lo tuyo, ¿verdad?",
      "En tu trabajo no saben quién eres realmente.",
      "Si me dejas, todos se enteran.",
      "Voy a decirle a tus papás que estás conmigo.",
      "Voy a subir una foto nuestra para que se enteren.",
      "Te conviene portarte bien si no quieres que hable.",
      "Tú no estás lista para que sepan, pero yo sí puedo contarles.",
      "Me cansé de ser tu secreto.",
      "Voy a decir que eres lesbiana.",
      "Voy a decir que eres trans.",
      "Voy a contar que sales con mujeres.",
      "Voy a contar que sales con hombres.",
      "Voy a contar que no eres como aparentas.",
      "Tu familia debería saber la verdad.",
      "No me importa si no has salido del clóset.",
      "Si no haces lo que quiero, mando las capturas.",
      "Tengo pruebas de lo nuestro.",
      "Voy a etiquetarte para que todos vean.",
      "No voy a seguir ocultándome por ti.",
      "Te voy a sacar del clóset.",
      "Voy a contarle a tu ex lo que eres.",
      "Voy a hablar con tus amistades.",
      "Voy a hacer público lo nuestro.",
      "Si tienes miedo de que sepan, no debiste meterte conmigo.",
      "A ver si sigues negándolo cuando todos sepan.",
      "Voy a decir que solo usas a la gente para experimentar.",
      "Voy a contar tus cosas íntimas.",
      "Tu orientación ya no va a ser secreto.",
      "Tengo derecho a contar lo que vivimos."
    ]
  },
  {
    "sourceCategory": "7. Aislamiento",
    "category": "isolation",
    "phrases": [
      "Tus amigas te meten ideas.",
      "Tu familia no quiere verte feliz.",
      "No me gusta que salgas sin mí.",
      "Elige: ellos o yo.",
      "Desde que hablas con esa persona estás diferente.",
      "No quiero que le cuentes nuestras cosas a nadie.",
      "Tus amistades son una mala influencia.",
      "No necesitas a nadie más si me tienes a mí.",
      "Prefiero que no vayas a esa reunión.",
      "Esa amiga tuya te está dañando.",
      "Tu terapeuta te mete cosas en la cabeza.",
      "No me gusta que hables con tu familia sobre nosotros.",
      "Si sales, no vuelvas.",
      "Siempre priorizas a otros antes que a mí.",
      "Quiero que pases todo tu tiempo conmigo.",
      "No quiero que sigas en ese grupo.",
      "Ese espacio no te conviene.",
      "La gente solo quiere separarnos.",
      "Nadie te entiende como yo.",
      "Yo soy la única persona que realmente te quiere.",
      "No me gusta que tengas vida sin mí.",
      "Tus amigos no respetan nuestra relación.",
      "Si me amaras, dejarías de verlos.",
      "No vayas a terapia, eso es para gente débil.",
      "No hables con nadie de lo que pasa entre nosotros.",
      "Tus amigas son feministas resentidas.",
      "Tu comunidad te está confundiendo.",
      "No quiero que salgas con gente queer.",
      "No quiero que sigas a esas personas en redes.",
      "Quédate conmigo, afuera nadie te cuida como yo."
    ]
  },
  {
    "sourceCategory": "Amenaza de violencia física",
    "category": "threat",
    "phrases": [
      "Si sigues hablando, te voy a pegar.",
      "No me hagas perder la paciencia porque sabes cómo me pongo.",
      "Te voy a romper la cara si me vuelves a faltar el respeto.",
      "Un día de estos me vas a hacer reaccionar mal.",
      "Si sales por esa puerta, no respondo.",
      "Te voy a dar una lección para que aprendas.",
      "No me provoques porque puedo hacerte daño.",
      "Si me bloqueas, voy a ir a buscarte.",
      "Te juro que si me dejas, algo te va a pasar.",
      "No sabes de lo que soy capaz cuando me enojo.",
      "Te voy a agarrar cuando estés sola.",
      "Sigue así y vas a terminar mal.",
      "A mí nadie me humilla, acuérdate.",
      "Si te veo con alguien más, los reviento a los dos.",
      "Te voy a hacer pagar por lo que me hiciste.",
      "No me obligues a levantar la mano.",
      "Si no contestas, voy a tu casa y arreglamos esto a mi manera.",
      "Voy a esperarte afuera.",
      "Si me denuncias, te va peor.",
      "Nadie te va a salvar si me haces enojar.",
      "Te voy a callar como sea.",
      "Si sigues llorando, te doy razones de verdad.",
      "Te voy a dejar marcada para que aprendas.",
      "Conmigo no se juega, te lo advierto.",
      "Si hablas con alguien de esto, te parto.",
      "Me dan ganas de estrellarte el celular en la cara.",
      "No me importa hacer un escándalo donde estés.",
      "Si no vuelves conmigo, voy a hacer una locura.",
      "Te voy a encontrar aunque te escondas.",
      "La próxima vez no voy a controlarme."
    ]
  },
  {
    "sourceCategory": "9. Violencia Patrimonial",
    "category": "economic",
    "phrases": [
      "Si te vas, no te doy ni un centavo.",
      "Todo lo que tienes es gracias a mí.",
      "Ese celular lo pagué yo, así que es mío.",
      "Si terminamos, me devuelves todo lo que te compré.",
      "No vas a trabajar porque yo mantengo esta casa.",
      "Tu plata también es mía.",
      "No tienes derecho a gastar sin preguntarme.",
      "Dame tu tarjeta, tú no sabes administrar.",
      "Yo manejo tu sueldo porque tú eres irresponsable.",
      "Si sales, te quito las llaves.",
      "No te voy a dejar entrar a la casa.",
      "Voy a romper tus cosas si me sigues ignorando.",
      "Te voy a botar la ropa a la calle.",
      "Voy a vender tus cosas para recuperar lo que gasté en ti.",
      "No te doy dinero hasta que te portes bien.",
      "Si no haces lo que digo, cancelo tu plan del celular.",
      "No vas a usar el carro si no me obedeces.",
      "Ese departamento está a mi nombre, así que tú no decides nada.",
      "Si me dejas, te quedas sin casa.",
      "Voy a quedarme con tus documentos.",
      "Sin tus papeles no vas a poder hacer nada.",
      "No pienso ayudarte con los gastos si sigues así.",
      "Te endeudaste por mi culpa, ahora arréglatelas.",
      "Saca un préstamo a tu nombre y yo después te pago.",
      "Firma esto, no preguntes tanto.",
      "No estudies, eso es perder plata.",
      "No necesitas trabajar, necesitas obedecer.",
      "Voy a dañar tu computadora para que dejes de hablar con esa gente.",
      "Si te vas, me quedo con todo.",
      "Tú no tienes nada propio mientras estés conmigo."
    ]
  }
] as const;

export const referenceExampleCount = referenceGroups.reduce((total, group) => total + group.phrases.length, 0);
